'use client'

import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <div>
      <Navbar />
      <main>{children}</main>
      <Footer/>
    </div>
    </html>
  )
}
